name = "sun-chun-portfolio"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

# 绑定 KV 数据库
[[kv_namespaces]]
binding = "DB"
id = "a19cc20f79ef4ae48d49c2510f52d433"

# 绑定 R2 存储桶
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "sun-chun-image"
